version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: desafio_conveniar
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DATABASE: desafio_conveniar
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      APP_PORT: 3000
    depends_on:
      - database
    ports:
      - "3000:3000"